site_name: 'yoneda'
docs_dir: src
nav:
  - General:
      - About: index.md

  - HoTT:
      - Common: hott/00-common.rzk.md
      - Paths: hott/01-paths.rzk.md
      - Homotopies: hott/02-homotopies.rzk.md
      - Equivalences: hott/03-equivalences.rzk.md
      - Sigma types: hott/04-sigma.rzk.md
      - Contractible: hott/05-contractible.rzk.md
      - Fibers: hott/06-fibers.rzk.md
      - Propositions: hott/07-propositions.rzk.md
      - Trivial fibrations: hott/08-trivial-fibrations.rzk.md

  - Simplicial HoTT:
      - Simplicial Type Theory: simplicial-hott/03-simplicial-type-theory.rzk.md
      - Extension Types: simplicial-hott/04-extension-types.rzk.md
      - Segal Types: simplicial-hott/05-segal-types.rzk.md
      - 2-Category of Segal Types: simplicial-hott/06-2cat-of-segal-types.rzk.md
      - Discrete Types: simplicial-hott/07-discrete.rzk.md
      - Covariantly Functorial Type Families: simplicial-hott/08-covariant.rzk.md
      - The Yoneda Lemma: simplicial-hott/09-yoneda.rzk.md
      - Cocartesian Families: simplicial-hott/12-cocartesian.rzk.md

markdown_extensions:
  - mdx_math

theme:
  name: readthedocs
  highlights: false # we override default highlights in custom_theme/
  custom_dir: custom_theme/
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
