site_name: "yoneda"
docs_dir: src
nav:
  - General:
    - About: index.md

  - HoTT:
      - Common: hott/0-common.md
      - Paths: hott/1-paths.md
      - Homotopies: hott/2-homotopies.md     
      - Equivalences: hott/3-equivalences.md
      - Contractible: hott/4-contractible.md
      - Sigma types: hott/5-sigma.md
      - Trivial fibrations: hott/6-trivial-fibrations.md
      - Fibers: hott/7-fibers.md

  - Simplicial HoTT:
      - Simplicial Type Theory: simplicial-hott/3-simplicial-type-theory.md
      - Extension Types: simplicial-hott/4-extension-types.md
      - Segal Types: simplicial-hott/5-segal-types.md
      - 2-Category of Segal Types: simplicial-hott/6-2cat-of-segal-types.md
      - Discrete Types: simplicial-hott/7-discrete.md
      - Covariantly Functorial Type Families: simplicial-hott/8-covariant.md
      - The Yoneda Lemma: simplicial-hott/9-yoneda.md
      
markdown_extensions:
  - mdx_math

theme:
  name: readthedocs
  highlights: false  # we override default highlights in custom_theme/
  custom_dir: custom_theme/
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css

