site_name: "yoneda"
docs_dir: src
nav:
  - General:
    - About: index.md

  - HoTT:
      - Common: hott/00-common.md
      - Paths: hott/01-paths.md
      - Homotopies: hott/02-homotopies.md     
      - Equivalences: hott/03-equivalences.md
      - Sigma types: hott/04-sigma.md
      - Contractible: hott/05-contractible.md
      - Fibers: hott/06-fibers.md
      - Trivial fibrations: hott/07-trivial-fibrations.md

  - Simplicial HoTT:
      - Simplicial Type Theory: simplicial-hott/03-simplicial-type-theory.md
      - Extension Types: simplicial-hott/04-extension-types.md
      - Segal Types: simplicial-hott/05-segal-types.md
      - 2-Category of Segal Types: simplicial-hott/06-2cat-of-segal-types.md
      - Discrete Types: simplicial-hott/07-discrete.md
      - Covariantly Functorial Type Families: simplicial-hott/08-covariant.md
      - The Yoneda Lemma: simplicial-hott/09-yoneda.md
      - Cocartesian Families: simplicial-hott/12-cocartesian.md
      
markdown_extensions:
  - mdx_math

theme:
  name: readthedocs
  highlights: false  # we override default highlights in custom_theme/
  custom_dir: custom_theme/
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css

