name: File formatting

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          # Only check changed files. Only works when the checkout action is set to fetch depth '0'
          only_changed: True
          prettier_options: --check **/*.{md,json,yaml,yml}
