name: Typecheck with latest Rzk

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches:
      - main
  # and pull request events
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check formalisations
    steps:
      - uses: actions/checkout@v3

      - name: Typecheck Rzk files
        uses: rzk-lang/rzk-action@v1
        with:
          rzk-version: latest
          # rzk-version: v0.4.1.1   # example of a specific version
